version: '3'

services:
  app:
    container_name: app_server
    build:
      context: ./

  server:
    container_name: proxy_server
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app